### ISSUE TITLE
Cannot find module issue

### ISSUE THREAD

**Issue by dderjoel** [jsdevtom/truegin#1]
I npm installed truegin and want to include it. However, I have the issue that VS-Code complains with the error message: "cannot find module 'truegin'" although I can see it in the node_modules directory.

A MWE can be seen here: 
https://github.com/dderjoel/trueginmwe

**Comment by jsdevtom** [comment]
Hey @dderjoel Thank you for taking the time to create an issue and many thanks for creating a 
minimum working example. This helped me solve the issue a lot faster. The problem is that I have created `truegin` to be compatible with multiple build systems (if you look in `node_modules/truegin/dist/` you'll see what I mean). For this reason, you have to import like so:

```
import {Rule} from "truegin/dist/lib/rule";

new Rule({
    conditions: {
        any: [{
            all: [{
                fact: 'gameDuration',
                operator: 'equal',
                value: 40
            }, {
                fact: 'personalFoulCount',
                operator: 'greaterThanInclusive',
                value: 5
            }]
        }, {
            all: [{
                fact: 'gameDuration',
                operator: 'equal',
                value: 48
            }, {
                fact: 'personalFoulCount',
                operator: 'greaterThanInclusive',
                value: 6
            }]
        }]
    },
    event: {  // define the event to fire when the conditions evaluate truthy
        type: 'fouledOut',
        params: {
            message: 'Player has fouled out!'
        }
    }
});
```

I know it's not the best but I'm really busy at the moment, so if you feel the imports could be improved, I'd welcome a pull request. :+1:

**Comment by dderjoel** [comment]
looking at your package.json, it says `  "typings": "dist/types/truegin.d.ts",` at the very end.

However, in the built package. There is no `dist/types` directory. 'But there is a `dist/lib` dir, which happens to contain the typings (truegin.d.ts). I think, changing this path in `package.json` to `  "typings": "dist/lib/truegin.d.ts",` would solve this issue.  At least it did (after Reloading VScode) when I changed this line in `\node_modules\truegin\package.json`.


However, I dont know It if breaks other stuff.

**Comment by dderjoel** [comment]
so I changed the package.json and also exported the Almanac interface (to have proper typings for in the callback of `engine.on(_, (event: any, almanac: Almanac) =>...`

I opened PR #2
